import ArticleWrapper from '@/components/layout/ArticleWrapper';
import Issuer1 from '@/public/Issuers1.png';
import Issuer2 from '@/public/Issuers2.png';
import Issuer3 from '@/public/Issuers3.png';
import Issuer4 from '@/public/Issuers4.png';
import Issuer5 from '@/public/Issuers5.png';
import Issuer6 from '@/public/Issuers6.png';
import Issuer7 from '@/public/Issuers7.png';
import Image from 'next/image';

export const metadata = {
  title: 'Managing Your Issuers',
  description: 'Learn how to manage, onboard, and configure issuers on the Credence platform.',
};

const toc = [
  { id: 'searching-and-filtering', title: 'Searching and Filtering', level: 2 as const },
  { id: 'adding-a-new-issuer', title: 'Adding a New Issuer', level: 2 as const },
  { id: 'understanding-the-issuer-directory', title: 'Understanding the Issuer Directory', level: 2 as const },
  { id: 'onboarding-business-info', title: 'Onboarding: Business Info', level: 2 as const },
  { id: 'onboarding-address', title: 'Onboarding: Address Details', level: 2 as const },
  { id: 'onboarding-workflow', title: 'Onboarding: Workflow Configuration', level: 2 as const },
  { id: 'onboarding-review', title: 'Onboarding: Final Review', level: 2 as const },
];

const content = `Welcome to the Issuers screen. Issuers are the specific organizations or departments authorized to create and distribute digital credentials to users. The Issuer Directory provides a searchable, sortable list of all onboarded issuers with key information at a glance. You can onboard new issuers through a guided four-step process covering Business Info, Address, Workflow Configuration, and Final Review. The workflow step allows deep customization of wallet settings, identity verification, credential templates, and authentication methods. Once reviewed, clicking Create Issuer finalizes the onboarding.`;

export default function Page() {
  return (
    <ArticleWrapper href="/platform/iwc-portal/issuers" title="Managing Your Issuers" contentText={content} toc={toc}>
      <p>
        Welcome to the <strong>Issuers</strong> screen. &ldquo;Issuers&rdquo; are the specific organizations or departments authorized to create and distribute digital credentials to users. This page serves as your central hub for viewing, searching, and onboarding new issuers into the Credence platform.
      </p>
<Image src={Issuer1} alt="" />
<br></br>
      {/* <img
        src="/platform/page-06.png"
        alt="Issuers list view showing the issuer directory with columns for name, status, credentials, onboarded date, templates, and actions"
        style={{ width: '100%', borderRadius: '8px', border: '1px solid #E5E5E3', margin: '1.5rem 0' }}
      /> */}

      <h2 id="searching-and-filtering">Searching and Filtering</h2>
      <p>
        The Issuers screen provides two levels of search to help you quickly find what you need:
      </p>
      <ul>
        <li><strong>Local Search Bar:</strong> Located directly above the issuer table, this field is labeled <em>&ldquo;Search by issuer name...&rdquo;</em> and filters the directory in real time as you type.</li>
        <li><strong>Global Search:</strong> The top navigation bar includes a broader <em>&ldquo;Search applications...&rdquo;</em> field that searches across the entire platform.</li>
      </ul>

      <h2 id="adding-a-new-issuer">Adding a New Issuer</h2>
      <p>
        To begin onboarding a new issuer, click the <strong>+ Onboard Issuer</strong> button (orange) located in the top-right corner of the page. This launches the guided onboarding wizard described in the sections below.
      </p>

      <h2 id="understanding-the-issuer-directory">Understanding the Issuer Directory</h2>
      <p>
        The Issuer Directory displays all onboarded issuers in a table with the following columns:
      </p>
      <ul>
        <li><strong>ISSUER:</strong> The organization or department name.</li>
        <li><strong>STATUS:</strong> Current state of the issuer, displayed as a green <em>Enabled</em> badge when active.</li>
        <li><strong>CREDENTIALS:</strong> The total volume of credentials generated by this issuer.</li>
        <li><strong>ONBOARDED:</strong> The date the issuer was added, shown in DD/MM/YYYY format.</li>
        <li><strong>TEMPLATES:</strong> The number of credential schemas assigned to this issuer. A dash (&mdash;) is shown if none have been assigned.</li>
        <li><strong>ACTIONS:</strong> Contains a <em>View</em> (eye icon) button to inspect the issuer&rsquo;s details, and a <em>Toggle switch</em> to enable or disable the issuer.</li>
      </ul>

      <h2 id="onboarding-business-info">Onboarding: Business Info</h2>

      <Image src={Issuer2} alt="" />
<br></br>

      <p>
        The onboarding wizard uses a <strong>4-step progress tracker</strong>: <em>Business Info &rarr; Address &rarr; Workflow &rarr; Review</em>. Step 1 collects the issuer&rsquo;s core organizational details.
      </p>
      <p><strong>Required fields:</strong></p>
      <ul>
        <li><strong>Tenant (*):</strong> Select the parent organization from a dropdown.</li>
        <li><strong>Business Name (*):</strong> The official, public-facing name of the issuer.</li>
        <li><strong>Email Address (*):</strong> The primary contact email for the issuer.</li>
        <li><strong>Phone Number (*):</strong> The official phone number, including country code.</li>
        <li><strong>Logo (optional):</strong> Provide a logo via URL or direct upload (toggle between the two modes).</li>
      </ul>
      <p>
        Click <strong>Next &gt;</strong> to proceed to the Address step.
      </p>

      <h2 id="onboarding-address">Onboarding: Address Details</h2>

      <Image src={Issuer3} alt="" />
<br></br>

      <p>
        In Step 2, the Business Info step shows a green checkmark indicating completion, and the Address step is highlighted as active. Fill in the issuer&rsquo;s physical address.
      </p>
      <p><strong>Required fields:</strong></p>
      <ul>
        <li><strong>Street Address (*)</strong></li>
        <li><strong>City (*)</strong></li>
        <li><strong>State / Province (*)</strong></li>
        <li><strong>ZIP / Postal Code (*)</strong></li>
        <li><strong>Country (*)</strong></li>
      </ul>
      <p>
        Click <strong>Next &gt;</strong> to proceed, or <strong>&lt; Back</strong> to return to Business Info.
      </p>

      <h2 id="onboarding-workflow">Onboarding: Workflow Configuration</h2>

      <p>
        Step 3 is the most comprehensive part of onboarding. It contains <strong>four expandable configuration sections</strong>:
      </p>

      <h3>Step 1: Wallet Configuration</h3>
      <Image src={Issuer4} alt="" />
<br></br>
      <ul>
        <li><strong>Client ID &amp; API Access:</strong> Auto-generated credentials for programmatic access.</li>
        <li><strong>Branding:</strong> Upload a logo and set a color scheme (hex code).</li>
        <li><strong>Basic Settings:</strong> Toggle switches for OTP Authentication and Show Email Address Field.</li>
        <li><strong>Wallet Security:</strong> Configure Security Code (PIN) and Fingerprint Authentication.</li>
        <li><strong>Document Proofs:</strong> Set the Primary Document (ID Proof &mdash; required dropdown) and an optional Secondary document.</li>
        <li><strong>Additional Checks:</strong> Enable Face Match (with provider dropdown), Liveness, Document Capture, Additional Documents Photo Capture.</li>
        <li><strong>Additional Data Collection:</strong> Options for Mother&rsquo;s Name, Consent Capture with Terms &amp; Conditions, and Store Multiple Credentials.</li>
      </ul>

      <h3>Step 2: IDV Configuration</h3>
      <Image src={Issuer5} alt="" />
<br></br>
      <p>Toggle switches to enable or disable each identity verification module:</p>
      <ul>
        <li>Face Match</li>
        <li>Liveness</li>
        <li>Document Authentication</li>
        <li>OCR &amp; Extraction</li>
        <li>Primary Document Deduplication</li>
        <li>Biometric 1:1 with Selfie:Document</li>
        <li>Biometric 1:N with ABIS</li>
        <li>SOR Check</li>
        <li>AML Screening</li>
        <li>Review &mdash; Manual</li>
        <li>Additional Document Check</li>
      </ul>

      <h3>Step 3: Credential Configuration</h3>
      <Image src={Issuer6} alt="" />
<br></br>
      <p>
        Select which credential templates this issuer is authorized to use via a dropdown selector.
      </p>

      <h3>Step 4: Auth Configuration</h3>
      <ul>
        <li>Allow In-Person Verification</li>
        <li>Allow Remote Verification</li>
        <li>OTP Authentication</li>
        <li>Pass Phrase (Mother&rsquo;s Name Validation)</li>
        <li>Proof of Presence (Face Auth)</li>
      </ul>
      <p>
        Click <strong>Next &gt;</strong> to proceed to the Final Review.
      </p>

      <h2 id="onboarding-review">Onboarding: Final Review</h2>

      <Image src={Issuer7} alt="" />
<br></br>

      <p>
        In the Review step, all four progress steps display green checkmarks. The page presents a <strong>read-only summary</strong> of everything you configured:
      </p>
      <ul>
        <li><strong>Business Info:</strong> Name, Email, Phone.</li>
        <li><strong>Address:</strong> Street, City, State, ZIP, Country.</li>
        <li><strong>Configuration:</strong> Status confirmation that all settings have been configured.</li>
      </ul>
      <p>
        Click <strong>Create Issuer</strong> (orange button) to finalize the onboarding, or <strong>&lt; Back</strong> to return and edit any previous step.
      </p>
    </ArticleWrapper>
  );
}
